### ISSUE TITLE
passing a resume that needs conversion returns an incomplete file name

### ISSUE THREAD

**Issue by philbaylog** [bcary/Vestn_Backend#10] opened 2012-06-28 16:17 UTC

**Comment by bcary** [comment] 2012-06-28 21:02
This was an issue caused by the fix for the last issue. This issue now fixed. Hopefully no more issues were caused. ("Yo dawg, I heard you like issues, so I put an issue in your issue so you can bug-fix while you bug-fix." --Alvin Nathaniel Joiner)

**Closed as completed by bcary** 2012-06-28 21:02 UTC
Labels: bug
